import { StyleSheet } from "react-native";

const styles = (theme) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: theme.white,
            padding: 16,
        },
        filterContainer: {
            marginBottom: 20,
            padding: 16,
            backgroundColor: theme.background,
            borderRadius: 12,
            shadowColor: theme.black,
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.2,
            shadowRadius: 8,
            elevation: 4,
            marginHorizontal: 8,
            borderColor: theme.primary,
            borderWidth: 1,
        },
        datePickerContainer: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginBottom: 12,
        },
        filterTitle: {
            fontSize: 20,
            fontWeight: '600',
            color: theme.text,
            marginBottom: 12,
            textAlign: 'center',
            textTransform: 'uppercase',
        },
        filterTitleS: {
            fontSize: 18,
            fontWeight: '500',
            color: theme.text,
            textAlign: 'center',
            textTransform: 'uppercase',
            marginBottom: 8,
        },
        searchContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 16,
            backgroundColor: theme.white,
            borderRadius: 8,
            elevation: 5,
            paddingHorizontal: 12,
            borderColor: theme.primary,
            borderWidth: 1,
            flex: 1,
        },
        searchIcon: {
            marginRight: 8,
        },
        searchInput: {
            flex: 1,
            height: 40,
            fontSize: 16,
        },
        statusFilterContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 10,
        },
        picker: {
            flex: 1,
            height: 50,
            borderColor: theme.primary,
            color: theme.black,
            borderWidth: 1,
            borderRadius: 8,
            marginBottom: 12,
        },
        dateButton: {
            flex: 1,
            marginHorizontal: 5,
            paddingVertical: 10,
            backgroundColor: theme.primary,
            borderRadius: 8,
            alignItems: "center",
            justifyContent: 'center',
            shadowColor: theme.black,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 2,
        },
        dateButtonText: {
            color: theme.white,
            fontWeight: "bold",
        },
        buttonContainer: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            gap: 10,
        },
        filterButton: {
            flex: 1,
            backgroundColor: theme.secondary,
            paddingVertical: 14,
            borderRadius: 8,
            alignItems: 'center',
            justifyContent: 'center',
            shadowColor: theme.black,
            shadowOffset: { width: 0, height: 3 },
            shadowOpacity: 0.1,
            shadowRadius: 6,
            elevation: 3,
        },
        fecharCaixaButton:{
            flex: 1,
            backgroundColor: theme.danger,
            paddingVertical: 14,
            borderRadius: 8,
            alignItems: 'center',
            justifyContent: 'center',
            shadowColor: theme.black,
            shadowOffset: { width: 0, height: 3 },
            shadowOpacity: 0.1,
            shadowRadius: 6,
            elevation: 3,
        },

        filterButtonText: {
            color: theme.white,
            fontWeight: "bold",
        },
        orderCard: {
            backgroundColor: theme.white,
            padding: 16,
            marginVertical: 10,
            borderRadius: 12,
            shadowColor: theme.black,
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.1,
            shadowRadius: 8,
            elevation: 2,
            borderBottomColor: theme.border,
            borderBottomWidth: 1,
        },
        orderText: {
            fontSize: 16,
            color: theme.text,
            marginBottom: 8,
        },
        cancelButton: {
            marginTop: 10,
            padding: 10,
            backgroundColor: theme.danger,
            borderRadius: 8,
            alignItems: 'center',
            justifyContent: 'center',
        },
        cancelButtonText: {
            color: theme.white,
            fontWeight: "bold",
        },
        emptyMessage: {
            textAlign: "center",
            fontSize: 16,
            color: theme.secondary,
            marginTop: 20,
        },
    });

export default styles;
